title:        jagm's personal page

baseurl:          ''

permalink:        /post/:year-:month-:day-:title:output_ext

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:path

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-redirect-from
